Repository WashU-Astroparticle-Lab/straxion, pull requests merged in 2025-07, with the labels that each got.

#2 Base context for QUALIPHIDE
  straxion/__init__.py
  straxion/contexts.py
  straxion/plugins/__init__.py
  tests/test_contexts.py
Labels: enhancement

#6 Records
  .gitignore
  straxion/__init__.py
  straxion/plugins/__init__.py
  straxion/plugins/raw_records.py
  straxion/plugins/records.py
  straxion/test_utils.py
  straxion/utils.py
Labels: enhancement

#7 Test records
  .github/workflows/pytest.yml
  straxion/plugins/records.py
  tests/test_raw_records.py
  tests/test_records.py
Labels: enhancement

#8 Debug pulse kernel
  straxion/plugins/records.py
  tests/test_records.py
Labels: bug

#9 Hits (pulse bank)
  .gitignore
  straxion/plugins/__init__.py
  straxion/plugins/hits.py
  straxion/plugins/raw_records.py
  straxion/plugins/records.py
  straxion/utils.py
Labels: enhancement

#13 Downgrade DATA_DTYPE to f4
  straxion/plugins/records.py
  straxion/utils.py
  tests/run_test_example.py
  tests/test_raw_records.py
  tests/test_records.py
Labels: bug

#15 Technical robustness hits.py tests
  straxion/plugins/hits.py
  tests/test_hits.py
Labels: test

#18 Data structure diagram `v0.0.0`
  straxion/plugins/README.md
Labels: documentation
